###############################################################################################################
# BEGIN CHANGE BLOCK
################################################################################################################
name: "Digital Nomad Claire"
title: "Digital Nomad Claire"
description: "Remote worker, traveller, and digital nomad expert"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'G-S27FVDHBJT'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-8155662166654237"
adsense-data-ad-slot: "1363087678"

authors:
  claire:
    name: claire 
    display_name: Claire Lago
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    avatar: 'assets/images/avatar.png'
    email: todo@change.com
    web: https://www.todo.change.com
    twitter: https://twitter.com/changeme
    description: ""

###############################################################################################################
# END CHANGE BLOCK
################################################################################################################
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

include:
  - ads.txt

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
paginate: 6
paginate_path: /page:num/
    
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

showjumbotron: false

showcomments: false

showauthorsocial: false

lazyimages: "disabled"

exclude: [changelog.md, LICENSE.md, README.md, Gemfile, Gemfile.lock]
